### ISSUE TITLE
 ERROR  Cannot start nuxt:  Cannot read properties of undefined (reading 'options')

### ISSUE THREAD

**Issue by MahsaGoudarzi** [madmod/nuxt-view-select#24]
Hey I just did what it has in the doc
`yarn add nuxt-vue-select`
then I added 
`modules: [
    "nuxt-vue-select",
  ],`  
in my nuxt config
but it doesn't work and has this issue :
`
 ERROR  Cannot restart nuxt:  Cannot read properties of undefined (reading 'options')

  at _default (node_modules/nuxt-vue-select/lib/module.js:11:13)
  at installModule (node_modules/@nuxt/kit/dist/index.mjs:452:21)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:2476:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6824:9)
  at async _applyPromised (node_modules/nuxi/dist/chunks/dev.mjs:6737:10)

`

package json: 
`{
  "name": "hey",
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@vuelidate/core": "^2.0.2",
    "@vuelidate/validators": "^2.0.2",
    "autoprefixer": "^10.4.14",
    "nuxt": "^3.3.2",
    "postcss": "^8.4.21",
    "sass": "^1.62.0",
    "tailwindcss": "^3.2.7"
  },
  "dependencies": {
    "@funken-studio/sitemap-nuxt-3": "^4.0.4",
    "@nuxt/kit": "^3.3.2",
    "click-outside-vue3": "^4.0.1",
    "nuxt-jsonld": "^2.0.7",
    "nuxt-vue-select": "^0.1.4",
    "vue-i18n": "^9.2.2",
    "vue-toastification": "next"
  },
  "packageManager": "yarn@3.5.0"
}`

How can I solve it?

**Comment by Rettend** [comment]
same

**Comment by cpiautoltd** [comment]
Same issue here

**Comment by vinceTheProgrammer** [comment]
Same issue but it's
`Cannot read properties of undefined (reading 'nuxt-vue-multiselect')`
for me

**Comment by aleksejantipov** [comment]
how to fix it?

**Comment by cesarkmelo** [comment]
I have the same error here, but it looks like this repo is abandoned
